language: python
os:
  - linux
python:
  - '2.7'
  - '3.5'
  - '3.6'
env:
  - TWINE_USERNAME=informaticsmatters
  - secure: Ota73pyTupnO8A/O8wKOTPRX7YcqD1fBVGMvoKc1HyQDMsTPgdM+bcyMFFCtml4OMuQNSx6nKUmfuovIWXvf4FRurLhsQ/TLBEPIz+WB8ryJjfBPPE3YIDCd5gKQIpop4u/BFHDHH2McNreh5WLYBTVswB6RJ1O/g0MuqpGDJ84nDTExjDD3qK7TJi8HGvUF9aFTX99TdMLUTQMnBwnOnheBdJBLCqj/cfZ8FxByqf1DXMqf2L9LQPgCCMS1xtd6bn1Xm/cTkwuowTXNDuiVao96fn/rAExl9c5X8FitgDBRdTSFoB6TIR5bhIKlLv84THhJuTxi5NJx2yVMD6vvruKYSksUUb63wJSwdDaqEKm+V9qRjN3pYmzcG/ngqrdwV14gxFjZ+3Q/jIfZI6fC5xueD4pWNaUm0j+RtxPBaDIw8s0uhVkJ1URKuvHzLr3sFAzZwr4vBY0DiqeXORa/NCvgHfsJHRlF/WzTLgQwUFai9PtlBCEi1zPZp1Q75ExklAJkAqwfetWY+eCw1KPbhOm2n3EevoBVVOjiY5u2yRV6u+nf/18lMfWuVFT+2LLcdXrgvCdw1VousMhsnm9+SBbeSxRLnv7D8lN2KVRm7fUWu3AqjfL/tEkltiaxi6zt7vd05ecIsnaGaBVxlGMUog6f7EZTE9rESpT+CjrCOI4=
branches:
  only:
    - "/.*/"
before_deploy:
  - cd src/python
deploy:
  proivider: pypi
  distributions: "bdist_wheel"
  on:
    branch: master
    tags: true
install:
  - pip install -r requirements.txt
  - pip install -r package-requirements.txt
  - cd mock-rdkit
  - python setup.py install
  - cd ..
script:
  - cd src/python
  - coverage run setup.py test
  - coverage report
  - pyroma .
  - python setup.py bdist_wheel
