language: python

python:
- "2.7"
- "3.5"
- "3.6"

branches:
  only:
  - /.*/

script:
- pip install -r package-requirements.txt
- cd mock-rdkit
- python setup.py install
- cd ../src/python
- python setup.py test
- pyroma .
- python setup.py bdist_wheel
