---

# The pipelines-utils Travis CI/CD configuration.
# Here we concentrate on the src/python part of the repository.
# where we run coverage testing and then deploy when tagged.
#
# We avoid running pylint at the moment because the vast majority of the
# code is legacy and fails a number of best-practice tests.

language: python

os:
- linux

# Our build stages.
# (`test` is basically a travis default default so we don't need to name it).
# But we do want a `deploy` stage that only runs if the the commit is tagged
# and it's the master branch.
stages:
- name: deploy
#- name: deploy
#  if: tag is present and branch = master

# Run Travis on all branches
# (normally it only runs on master)
branches:
  only:
  - "/.*/"

# Installation steps.
# We have more than one requirements file and need to install
# a mock version of dependent packages in order to run our tests.
install:
- pip install -r requirements.txt
- pip install -r package-requirements.txt
- cd ${TRAVIS_BUILD_DIR}/mock-rdkit
- python setup.py install

# Test/build execution steps...
# All in the default 'test' stage.
script:
- cd ${TRAVIS_BUILD_DIR}/src/python
- coverage run setup.py test
- coverage report
- pyroma .
- python setup.py bdist_wheel

# Execution jobs.
# Let's run the script against various Python versions
# and then move to our deploy stage. Travis will only run the deploy stage
# when the test stages have passed. Deployment will also only execute
# if this triggering commit is tagged and we're on the master branch.
jobs:
  include:
  - python: 2.7
  - python: 3.5
  - python: 3.6
    env:
    - TWINE_USERNAME=informaticsmatters
    - secure: b5P02Bw2sZQORqDR+hTm92NMSkYiUpXDngnvUckkJWbC2GnAKjrDjqP5op4YQhMfb29U+OdkbYQyOoMmTbQe8K+e0eoaHL1spTER7eqO5wHG0d0ebJY6PEm/nmZDlGiOlMbL1HnBNqaqWfvKYDV4gAWHkRDc4+kWb+/k6tqa6Rkk2tp5LjTEQqAYM2ihGNmU6kfJhqWjjDN/yvnYQIc4KQ7PZKF8yaAE5XHEv81QSsVohxCjKkM7acOx2hahG7RA5SVLj/YMdOzNJSuO+yzBGnZDexg4RtWcTcF896ZDpXPjHa9bS9jL1dPbgvH/hY+fBaxHUGn0WrYdpbD+1x7OGDScg0ySSfk+I/a9FoF8Nm3zYsL9sJGFaV5xrCs7rBFYvHbEcbBNF316PD7gJoOBEYCHdtLyAaqXpa92XUiH/n5oRBMDoqSnfgo2CsrS/6c8k634KkW9W+AsQsG8hFL1YAwuLzIK6H899DAINVojt3hpw8ryrOy5u5Zb2kEw+JGx7/FvZ8ZYLozuE6j4BWClSoWGPmxWMtBw84MSpAI2D/rcWJUV/VzwS9vWGe+uhl9ZPdXs2Yg7B0cihRXzu9iFSBR/1EgZENYoriORdNtWwdtcIsnaWCrH9bOVgYlEv7xoK02Vj36K/FAKIOesCmhOd1vUYosqJyQ50p1Z9C7L0GY=

  - stage: deploy
    python: 3.6
    # Our module and setup.py is not located in the root of the project.
    # Move to it before we deploy.
    before_deploy:
    - cd ${TRAVIS_BUILD_DIR}/src/python
    deploy:
      proivider: pypi
      user: informaticsmatters
      password:
        secure: "FgNbSAEtomSpBwIF26CXF1f+8z4FWAYVC6aae5ZTTRvUA9rjhj64OKzdxe4hRYnrw4PLk615wNbJSwDm4NQds8hX2MJxwSa+oLOdwuDXq4dYikJuT1YIaMgNAKN+gjLNEf+vSpLDbyG8QIJgLgjEHVx5rxNrvGglXPg52jN1mVZvoL79UXgHzjFmlG0UuaU5AEUL57Sv9NX5iOUAdHWr+v5hNmeAq0Nz92e4O2byLoizCsdbPd20K9P56aL/Lo/hwO1mVcR5BLz2/oQBynMiQGlp+yrg+lbxc3HSYUaM/hMvwK08Y5ITkQzoqNoClyeuw43FsqInvs8DjGRFCZNOpf1gWSNY7bHjIUvCqVLPZu5Cd76B0SQCd8guFwDawOc0HWKc1g7P1XZ3h2BH6XkiPohJT2zSdYboRwSHY658dobJXcj5Q4ZUp73qhRoKb/8XXVUzQwYCp2Hp3dRvuGjJXVCb5VX4VzJQXJqMHjK8+Z0QzPvN+YOoAEFgE3Yxjykov3TeSs+AHdLTHq9osWv/zAPGSVxzBjgFnUp8qT8iwz5gPlYqukHudvQx2nJAH73CVSDJYCiecYqVFdPxFw7xCg2MYCqlrlvONMsSEPGssyngX8gKzrSQxmunCf3r0QzHl9/mXvndHEOQyI1NmzNHPB8+FItYT1UlOnIcr9eOC8k="
      distributions: bdist_wheel
