language: python

python:
  - "2.7"
  - "3.6"

branches:
  only:
    - /.*/

stages:
  - test
  - package

install:
  - pip install -r requirements.txt
  - pip install -r package-requirements.txt

jobs:
  include:
    - script: cd mock-rdkit
    - script: python setup.py install
    - script: cd ../src/python
    - script: python setup.py test
    - stage: package
      script:
        - cd src/python
        - pyroma .
        - python setup.py bdist_wheel
