language: python

python:
- "2.7"
- "3.6"

branches:
  only:
  - /.*/

stages:
- test
- package

jobs:
  include:
    - stage: test
      script:
        - cd mock-rdkit
        - python setup.py install
        - cd ../src/python
        - python setup.py test
        - cd ../..
    - stage: package
      script:
        - pip install -r package-requirements.txt
        - cd src/python
        - pyroma .
        - python setup.py bdist_wheel
